name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /www/wwwroot/myxy99.github.io
            git reset --hard 
            git pull
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          pass: ${{ secrets.PASSWORD }}